name: employee_management_app
description: Employee Management System Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.0
  open_file: ^3.2.1
  path: ^1.8.0
  mime: ^1.0.0
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
