# Generated by Django 5.1.7 on 2025-03-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="annual_leave_hours",
            field=models.DecimalField(decimal_places=1, default=160, max_digits=6),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="personal_leave_hours",
            field=models.DecimalField(decimal_places=1, default=40, max_digits=6),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="sick_leave_hours",
            field=models.DecimalField(decimal_places=1, default=80, max_digits=6),
        ),
    ]
